//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.11

pub mod prelude;

pub mod author;
pub mod game;
pub mod manga;
pub mod manga_chapter;
pub mod media_library;
pub mod movie;
pub mod photo;
pub mod photo_album;
pub mod photo_album_item;
pub mod photo_exif;
pub mod user;
